# Generated by Django 5.0.6 on 2024-06-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_avaliable', models.BooleanField(default=False)),
                ('last_avaliable_date', models.DateTimeField(null=True)),
                ('display_image', models.ImageField(upload_to='images/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(null=True)),
                ('display_image', models.ImageField(upload_to='images/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(null=True)),
                ('display_image', models.ImageField(upload_to='images/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
